// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEmployee(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['EmployeeService']['AddEmployee'](arg1, arg2, arg3, arg4);
}

export function DeleteEmployee(arg1) {
  return window['go']['backend']['EmployeeService']['DeleteEmployee'](arg1);
}

export function GetEmployee(arg1) {
  return window['go']['backend']['EmployeeService']['GetEmployee'](arg1);
}

export function GetEmployees() {
  return window['go']['backend']['EmployeeService']['GetEmployees']();
}

export function UpdateEmployee(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['EmployeeService']['UpdateEmployee'](arg1, arg2, arg3, arg4, arg5);
}
