// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddEmployee(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function DeleteEmployee(arg1:number):Promise<void>;

export function GetEmployee(arg1:number):Promise<backend.Employee>;

export function GetEmployees():Promise<Array<backend.Employee>>;

export function UpdateEmployee(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;
